### ISSUE TITLE
Bug: SSR Streaming Example: CSP Error

### ISSUE THREAD

**Issue by exellian** [sycamore-rs/sycamore#789]
**Describe the bug**
I was trying to run the SSR-Streaming example locally. So I created a new project and run it and it was working with SSR. When I tried using trunk serve on the example project and changed the main app code instead of hydrating to rendering the root component, i received a CSP Error:

![Image](https://github.com/user-attachments/assets/c44f21ee-9fb1-439c-8553-be3f936eb5d3)

For some reason the script and also the wasm are not executed and blocked by chrome.
I already tried to set appropiate headers in Trunk.toml as well as inside index.html without success:

```toml
[build]
inject_scripts = false
filehash = false

[watch]
ignore = ["src/server.rs"]

[serve]
headers = { "Content-Security-Policy" = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:;" }
```

```html
<!doctype html>
<html>

<head>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:;">
</head>

<body>
We do not use Trunk for rendering HTML since we are using SSR streaming.
</body>

</html>
```

**To Reproduce**

1. Clone the example code of ssr-streaming
2. Change the main.rs #[cfg_not_ssr] section:
`
#[cfg_not_ssr]
fn main() {
    console_error_panic_hook::set_once();
    let document = document();
    
    sycamore::render(app::Root); // render instead of hydration
}
`
3. trunk serve
4. open newest chrome version, and you should see that the script was blocked

**Environment**
- Sycamore: 0.9.1
- Browser: chrome, edge
- OS: Windows
